# Generated by Django 4.0.1 on 2022-02-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(blank=True, max_length=60, null=True)),
                ('descripcionUsuario', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
